//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Web.DTO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class account
    {
        public int id { get; set; }

        [Required(ErrorMessage ="Please Select Group Name")]
        public Nullable<int> groupid { get; set; }

        [Required(ErrorMessage = "Please Enter First Name")]
        public string name { get; set; }

        [Required(ErrorMessage = "Please Enter Last Name")]
        public string lname { get; set; }

        [Required(ErrorMessage = "Please Enter Company Name")]
        public string company { get; set; }
        public string website { get; set; }

        [Required(ErrorMessage = "Please Enter Email Address")]
        [EmailAddress(ErrorMessage = "Please Enter Your Valid Email Address")]
        public string email { get; set; }

        [Required(ErrorMessage = "Please Enter Your Address")]
        public string address1 { get; set; }
        public string address2 { get; set; }

        [Required(ErrorMessage = "Please Enter Your State")]
        public string state { get; set; }

        [Required(ErrorMessage = "Please Enter Your City")]
        public string city { get; set; }

        [Required(ErrorMessage = "Please Enter Your PostCode")]
        public string postcode { get; set; }

        [Required(ErrorMessage = "Please Select Your Country")]
        public string country { get; set; }

        [Required(ErrorMessage = "Please Enter Your Phone")]
        public string phone { get; set; }

        [Required(ErrorMessage = "Please Enter Your Password")]
        public string password { get; set; }
        public string image { get; set; }
        public System.DateTime datecreated { get; set; }
        public int email_limit { get; set; }
        public string sms_limit { get; set; }
        public Nullable<System.DateTime> lastlogin { get; set; }

        [Required(ErrorMessage = "Please Select Your Email Permission")]
        public int email_perm { get; set; }
        [Required(ErrorMessage = "Please Select Your SMS Permission")]
        public int sms_perm { get; set; }
        public Nullable<int> online { get; set; }
        public string status { get; set; }
        public string pwresetkey { get; set; }
        public int pwresetexpiry { get; set; }
        public string emailnotify { get; set; }

        [Required(ErrorMessage = "Please Select Your Email Gateway")]
        public string email_gateway { get; set; }

        [Required(ErrorMessage = "Please Select Your SMS Gateway")]
        public string sms_gateway { get; set; }
        public int parent { get; set; }
    }
}
