//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Web.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string status { get; set; }
        public string email { get; set; }
        public string image { get; set; }
        public int roleid { get; set; }
        public Nullable<System.DateTime> lastlogin { get; set; }
        public string pwresetkey { get; set; }
        public Nullable<int> pwresetexpiry { get; set; }
        public string emailnotify { get; set; }
        public Nullable<int> online { get; set; }
    }
}
