//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Web.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_logs
    {
        public int id { get; set; }
        public int userid { get; set; }
        public string email { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int send_by { get; set; }
    }
}
