//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Web.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_templates
    {
        public int id { get; set; }
        public string tplname { get; set; }
        public int language_id { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public Nullable<bool> send { get; set; }
        public string core { get; set; }
        public Nullable<bool> hidden { get; set; }
    }
}
