//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Web.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_providers
    {
        public int id { get; set; }
        public string name { get; set; }
        public string host_name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string port { get; set; }
        public int status { get; set; }
    }
}
