//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Web.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class emsEntities : DbContext
    {
        public emsEntities()
            : base("name=emsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accgroup> accgroups { get; set; }
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<adminrole> adminroles { get; set; }
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<appconfig> appconfigs { get; set; }
        public virtual DbSet<email_logs> email_logs { get; set; }
        public virtual DbSet<email_providers> email_providers { get; set; }
        public virtual DbSet<email_templates> email_templates { get; set; }
        public virtual DbSet<email_transaction> email_transaction { get; set; }
        public virtual DbSet<int_country_codes> int_country_codes { get; set; }
        public virtual DbSet<invoiceitem> invoiceitems { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<manage_sender> manage_sender { get; set; }
        public virtual DbSet<payment_gateways> payment_gateways { get; set; }
        public virtual DbSet<sms_gateway> sms_gateway { get; set; }
        public virtual DbSet<sms_history> sms_history { get; set; }
        public virtual DbSet<sms_plan_feature> sms_plan_feature { get; set; }
        public virtual DbSet<sms_price_plan> sms_price_plan { get; set; }
        public virtual DbSet<sms_transaction> sms_transaction { get; set; }
        public virtual DbSet<supportdepartment> supportdepartments { get; set; }
        public virtual DbSet<ticketreply> ticketreplies { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<adminperm> adminperms { get; set; }
    }
}
