//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Web.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int id { get; set; }
        public int userid { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public System.DateTime datepaid { get; set; }
        public decimal subtotal { get; set; }
        public decimal total { get; set; }
        public string status { get; set; }
        public string paymentmethod { get; set; }
        public decimal tax { get; set; }
        public Nullable<decimal> discount { get; set; }
        public string note { get; set; }
    }
}
