//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Web.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_price_plan
    {
        public int id { get; set; }
        public string plan_name { get; set; }
        public decimal price { get; set; }
        public int popular { get; set; }
        public int status { get; set; }
    }
}
