//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Web.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int id { get; set; }
        public int did { get; set; }
        public int userid { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public System.DateTime date { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public string status { get; set; }
        public string admin { get; set; }
        public string replyby { get; set; }
        public string closed_by { get; set; }
    }
}
